---
- name: Check if pull central registry secret exists
  command: "{{ oc }} get secret pull-external-registry -n {{ project_name }}"
  register: pull_registry_secret
  ignore_errors: true
- name: Docker pull registry secret
  command: "{{ oc }} secrets new-dockercfg pull-external-registry --docker-username=unused --docker-password={{ hostvars['registry']['pulltoken'] }} --docker-email=unused -n {{ project_name }}"
  when: pull_registry_secret|failed
- name: Link docker pull registry secret
  command: "{{ oc }} secrets link default pull-external-registry --for=pull -n {{ project_name }}"
  when: pull_registry_secret|failed
