---
- name: Get registry push token value
  command: "{{ oc }} sa get-token builder -n {{ project_name }}"
  register: forpush
- name: Get pull token value
  command: "{{ oc }} sa get-token deployer -n {{ project_name }}"
  register: forpull
- set_fact:
    pushtoken: "{{ forpush.stdout }}"
    pulltoken: "{{ forpull.stdout }}"
