apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: release-pipeline
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: "release-pipeline"
  spec:
    source:
      type: "Git"
      git:
        uri: ${SOURCE_REPOSITORY_URL}
        ref: ${SOURCE_REPOSITORY_REF}
    strategy:
      type: "JenkinsPipeline"
      jenkinsPipelineStrategy:
          jenkinsfilePath: Jenkinsfile.production
    triggers: {}
parameters:
- description: The URL of the repository with your application source code.
  displayName: Git Repository URL
  name: SOURCE_REPOSITORY_URL
  required: true
  value: https://github.com/RHsyseng/jenkins-on-openshift.git
- description: Set this to a branch name, tag or other ref of your repository if you
    are not using the default branch.
  displayName: Git Reference
  name: SOURCE_REPOSITORY_REF
  value: master
