---
- name: Configure project authorization
  hosts: all
  roles:
    - role: auth
- name: Setup Jenkins
  hosts: dev
  roles:
    - role: jenkins
    - role: pusher
- name: Setup registry tokens
  hosts: stage
  roles:
    - role: puller
